import { Request, Response, Router } from "express";
import { upload_service } from "../services/file_upload.service";
import { _postController } from "./post.controller";

export const postRouter = Router();

postRouter
    .get('/', (req: Request, res: Response) => _postController.find(res, {}))
    .get('/:id', (req: Request, res: Response) => _postController.findOne(res, {_id: req.params.id}))
    .post('/', 
        upload_service.single('image'), // req.path -> contains the url were the files is being uploaded.
        (req: any, res, next) => {
            // image_url is generated by upload_service.
            // image_url is not available at frontend side.
            // so, we are setting the image_url inside the body so that it gets saved in database.
            req.body.image_url = req.path;
            next();
        },
        (req, res) => _postController.create(res, req.body))
    .patch('/:id', (req, res) => _postController.update(res, req.params.id, req.body))
    .delete('/:id', (req, res) => _postController.delete(res, req.params.id))